-- Fixfy partner contract templates (Terms of Use, Self-Billing, Contractor Service Agreement)
-- Generated by master-trade-portal/scripts/generate-partner-contracts-migration.mts

ALTER TABLE public.contract_versions DROP CONSTRAINT IF EXISTS contract_versions_contract_type_check;
ALTER TABLE public.contract_versions
  ADD CONSTRAINT contract_versions_contract_type_check
  CHECK (contract_type IN (
    'terms_of_use',
    'self_bill_agreement',
    'contractor_service_agreement',
    'workforce_service_agreement',
    'workforce_employment_contract'
  ));

-- Platform Terms of Use
UPDATE public.contract_versions SET is_active = false WHERE contract_type = 'terms_of_use' AND is_active = true;
INSERT INTO public.contract_versions (contract_type, version, title, body_html, is_active)
VALUES (
  'terms_of_use',
  '2026-06-09',
  'Platform Terms of Use',
  '<style>:root{--navy:#020040;--coral:#ED4B00;--ink:#1a1a1a;--grey:#555;--light:#f2f2f5;--line:#ccc;}
  *{box-sizing:border-box;}
  html{-webkit-print-color-adjust:exact;print-color-adjust:exact;}
  body{font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#e9e9ee;margin:0;line-height:1.5;font-size:11pt;}
  .page{background:#fff;max-width:820px;margin:24px auto;padding:48px 56px 64px;box-shadow:0 2px 16px rgba(0,0,0,.12);}
  header.brand{display:flex;justify-content:space-between;align-items:baseline;border-bottom:3px solid var(--coral);padding-bottom:10px;margin-bottom:6px;}
  header.brand .logo{font-weight:800;font-size:18pt;color:var(--navy);letter-spacing:1px;}
  header.brand .meta{font-size:8.5pt;color:var(--grey);}
  h1.title{font-size:24pt;color:var(--navy);font-weight:800;margin:24px 0 0;line-height:1.05;}
  h1.title .accent{color:var(--coral);display:block;}
  .lead{text-align:justify;margin:14px 0;}
  .party{font-weight:700;color:var(--navy);}
  .andword{font-style:italic;}
  h2.section{font-size:13pt;color:var(--navy);font-weight:700;margin:24px 0 8px;}
  p{text-align:justify;margin:8px 0;}
  .sub{font-weight:700;color:var(--navy);}
  ul.dash{list-style:none;margin:6px 0 10px;padding-left:24px;}
  ul.dash li{position:relative;padding-left:18px;margin:3px 0;text-align:justify;}
  ul.dash li::before{content:"\2013";color:var(--coral);position:absolute;left:0;font-weight:700;}
  .label{font-size:9pt;font-weight:700;color:var(--navy);text-transform:uppercase;letter-spacing:.5px;margin:16px 0 8px;}
  table.details{width:100%;border-collapse:collapse;margin:8px 0 4px;}
  table.details td{border:1px solid var(--line);padding:8px 12px;font-size:10pt;vertical-align:top;}
  table.details td.k{background:var(--light);font-weight:700;color:var(--navy);width:32%;}
  table.details td.v{height:14px;}
  .callout{background:var(--light);border-left:4px solid var(--coral);padding:12px 16px;margin:14px 0;font-size:10pt;}
  .execution{page-break-before:always;}
  h2.exec{font-size:18pt;color:var(--navy);font-weight:800;margin:8px 0 14px;}
  .sigwrap{display:flex;gap:0;border:1px solid var(--line);}
  .sigcell{flex:1;padding:16px;}
  .sigcell + .sigcell{border-left:1px solid var(--line);}
  .sigcell .h{font-weight:700;color:var(--navy);font-size:10.5pt;margin-bottom:4px;}
  .sigcell .org{font-size:10pt;margin:2px 0;}
  .sigline{border-bottom:1.5px solid var(--navy);height:34px;margin-top:14px;}
  .sigcap{font-size:8.5pt;color:var(--grey);margin-top:2px;}
  footer.foot{border-top:1px solid var(--line);margin-top:40px;padding-top:8px;display:flex;justify-content:space-between;font-size:8.5pt;color:var(--grey);}
  @media print{body{background:#fff;}.page{box-shadow:none;margin:0;max-width:100%;padding:0 12mm;}@page{size:A4;margin:14mm 0;}}</style>
<div class="page"><header class="brand"><div class="logo">FIXFY</div><div class="meta">Getfixfy Ltd &middot; Co. No. 15406523</div></header>
  <h1 class="title">PLATFORM<span class="accent">TERMS OF USE</span></h1>
  <p class="lead">These Platform Terms of Use (the &ldquo;Terms&rdquo;) govern access to and use of the Fixfy platform operated by <span class="party">GETFIXFY LTD</span>, a company incorporated in England and Wales under company number 15406523, with its registered office at 124 City Road, London EC1V 2NX, United Kingdom (&ldquo;Fixfy&rdquo;, the &ldquo;Company&rdquo;, &ldquo;we&rdquo; or &ldquo;us&rdquo;).</p>
  <p class="lead">By registering for, accessing or using the platform as a trade, contractor or service provider (the &ldquo;Partner&rdquo;, &ldquo;you&rdquo; or &ldquo;your&rdquo;), you agree to be bound by these Terms.</p>

  <div class="callout"><strong>Agency model.</strong> Fixfy operates as a disclosed agent that introduces maintenance and facilities jobs from business clients to vetted Partners. Fixfy is not the end client and does not itself perform the works. Fixfy facilitates introductions, coordination, invoicing and payment through the platform.</div>

  <h2 class="section">1.&nbsp;&nbsp;Definitions</h2>
  <ul class="dash">
    <li><strong>Platform</strong> &mdash; the Fixfy web and mobile applications, portal and related systems.</li>
    <li><strong>Client</strong> &mdash; a business that requests maintenance, repair or facilities services through the Platform.</li>
    <li><strong>Job</strong> &mdash; a specific unit of work requested by a Client and allocated to a Partner.</li>
    <li><strong>Partner Content</strong> &mdash; data, documents, certifications and information submitted by the Partner.</li>
  </ul>

  <h2 class="section">2.&nbsp;&nbsp;Eligibility and Vetting</h2>
  <p><span class="sub">2.1</span>&nbsp;&nbsp;The Partner warrants that it operates as an independent business and holds all licences, qualifications, insurance and certifications required to perform the Services lawfully in the United Kingdom, including where applicable Gas Safe, NICEIC, NAPIT, EICR and Fire Safety certifications.</p>
  <p><span class="sub">2.2</span>&nbsp;&nbsp;The Partner shall keep all certifications, insurance and qualification records current and shall upload valid evidence to the Platform on request. Fixfy may suspend a Partner whose records are expired, missing or unverifiable.</p>
  <p><span class="sub">2.3</span>&nbsp;&nbsp;Fixfy reserves the right to vet, approve, decline or remove any Partner at its discretion.</p>

  <h2 class="section">3.&nbsp;&nbsp;Use of the Platform</h2>
  <p><span class="sub">3.1</span>&nbsp;&nbsp;The Partner shall use the Platform only for legitimate business purposes connected to the provision of Services to Clients introduced by Fixfy.</p>
  <p><span class="sub">3.2</span>&nbsp;&nbsp;The Partner shall not misuse, disrupt, reverse-engineer, copy or attempt to gain unauthorised access to the Platform or its data.</p>
  <p><span class="sub">3.3</span>&nbsp;&nbsp;Access credentials are personal to the Partner and must be kept secure. The Partner is responsible for all activity under its account.</p>

  <h2 class="section">4.&nbsp;&nbsp;Jobs, Pricing and Payment</h2>
  <p><span class="sub">4.1</span>&nbsp;&nbsp;Jobs are presented to the Partner with either pre-set pricing or a request for a quote. The Partner is free to accept or decline any Job.</p>
  <p><span class="sub">4.2</span>&nbsp;&nbsp;All payment for Jobs must be processed through the Platform&rsquo;s integrated payment system. Fixfy applies its commission to each Job in accordance with the rates notified to the Partner.</p>
  <p><span class="sub">4.3</span>&nbsp;&nbsp;Invoicing for completed Jobs is handled by self-billing, governed by the separate Self-Billing Agreement which the Partner must accept.</p>
  <p><span class="sub">4.4</span>&nbsp;&nbsp;Any guarantee or service warranty offered by Fixfy applies only to Jobs booked, managed and paid through the Platform.</p>

  <h2 class="section">5.&nbsp;&nbsp;Anti-Circumvention</h2>
  <p><span class="sub">5.1</span>&nbsp;&nbsp;The Partner shall not solicit, divert or transact with a Client introduced through the Platform outside the Platform, whether directly or indirectly, for any Job that originated through Fixfy.</p>
  <p><span class="sub">5.2</span>&nbsp;&nbsp;The Partner shall not share, expose or use Client contact details to bypass the Platform. Breach of this clause may result in immediate suspension, removal and recovery of lost commission.</p>

  <h2 class="section">6.&nbsp;&nbsp;Standards and Conduct</h2>
  <p><span class="sub">6.1</span>&nbsp;&nbsp;The Partner shall perform all Services with reasonable skill and care, in compliance with applicable law, health and safety requirements and industry standards.</p>
  <p><span class="sub">6.2</span>&nbsp;&nbsp;The Partner shall meet agreed response windows, attendance windows and quality standards. Repeated failure may result in reduced Job allocation or removal.</p>

  <h2 class="section">7.&nbsp;&nbsp;Data and Records</h2>
  <p><span class="sub">7.1</span>&nbsp;&nbsp;Job history, Client records, documentation and operational data generated on the Platform remain the property of Fixfy and the relevant Client, and are made available to the Partner only for the purpose of delivering Services.</p>
  <p><span class="sub">7.2</span>&nbsp;&nbsp;Each party shall comply with applicable data protection law (including the UK GDPR and the Data Protection Act 2018) in respect of personal data processed through the Platform.</p>

  <h2 class="section">8.&nbsp;&nbsp;Independent Relationship</h2>
  <p><span class="sub">8.1</span>&nbsp;&nbsp;The Partner is an independent business. Nothing in these Terms creates any employment, worker, partnership, agency (beyond the disclosed introduction model) or joint-venture relationship between Fixfy and the Partner.</p>
  <p><span class="sub">8.2</span>&nbsp;&nbsp;The Partner is solely responsible for its own taxes, social security, insurance and obligations to its own personnel.</p>

  <h2 class="section">9.&nbsp;&nbsp;Liability</h2>
  <p><span class="sub">9.1</span>&nbsp;&nbsp;The Partner is solely responsible for the Services it performs and indemnifies Fixfy against claims arising from the Partner&rsquo;s acts, omissions, defective work or breach of these Terms.</p>
  <p><span class="sub">9.2</span>&nbsp;&nbsp;Nothing in these Terms limits liability for death or personal injury caused by negligence, fraud, or any liability that cannot be excluded by law.</p>

  <h2 class="section">10.&nbsp;&nbsp;Suspension and Termination</h2>
  <p><span class="sub">10.1</span>&nbsp;&nbsp;Fixfy may suspend or terminate a Partner&rsquo;s access at any time for breach of these Terms, expired certifications, or conduct that poses risk to Clients or the Platform.</p>
  <p><span class="sub">10.2</span>&nbsp;&nbsp;The Partner may stop using the Platform at any time. Obligations relating to confidentiality, anti-circumvention, data and accrued payment survive termination.</p>

  <h2 class="section">11.&nbsp;&nbsp;Changes to the Terms</h2>
  <p><span class="sub">11.1</span>&nbsp;&nbsp;Fixfy may update these Terms from time to time. Material changes will be notified through the Platform. Continued use after notification constitutes acceptance.</p>

  <h2 class="section">12.&nbsp;&nbsp;Governing Law</h2>
  <p><span class="sub">12.1</span>&nbsp;&nbsp;These Terms are governed by the laws of England and Wales. Disputes shall be subject to confidential arbitration in London under the LCIA Rules, with London as the seat and English as the language.</p>

  <div class="execution">
    <h2 class="exec">ACCEPTANCE</h2>
    <p>By clicking &ldquo;Sign&rdquo; / &ldquo;Accept&rdquo; in the Fixfy onboarding portal, or by signing below, the Partner confirms it has read, understood and agreed to these Platform Terms of Use.</p>
    <div class="sigwrap">
      <div class="sigcell">
        <div class="h">GETFIXFY LTD</div>
        <div class="org">Getfixfy Ltd</div>
        <div class="org">124 City Road, London EC1V 2NX</div>
        <div class="org">Co. No. 15406523</div>
        <div class="sigline"></div><div class="sigcap">Authorised signatory</div>
        <div class="sigline"></div><div class="sigcap">Date</div>
      </div>
      <div class="sigcell">
        <div class="h">THE PARTNER</div>
        <div class="org">&nbsp;</div>
        <div class="sigline"></div><div class="sigcap">Name / Business name</div>
        <div class="sigline"></div><div class="sigcap">Signature</div>
        <div class="sigline"></div><div class="sigcap">Date</div>
      </div>
    </div>
  </div>

  <footer class="foot"><span>Platform Terms of Use &middot; v2026 &mdash; Confidential</span><span>Getfixfy Ltd</span></footer></div>',
  true
);

-- Self-Billing Agreement
UPDATE public.contract_versions SET is_active = false WHERE contract_type = 'self_bill_agreement' AND is_active = true;
INSERT INTO public.contract_versions (contract_type, version, title, body_html, is_active)
VALUES (
  'self_bill_agreement',
  '2026-06-09',
  'Self-Billing Agreement',
  '<style>:root{--navy:#020040;--coral:#ED4B00;--ink:#1a1a1a;--grey:#555;--light:#f2f2f5;--line:#ccc;}
  *{box-sizing:border-box;}
  html{-webkit-print-color-adjust:exact;print-color-adjust:exact;}
  body{font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#e9e9ee;margin:0;line-height:1.5;font-size:11pt;}
  .page{background:#fff;max-width:820px;margin:24px auto;padding:48px 56px 64px;box-shadow:0 2px 16px rgba(0,0,0,.12);}
  header.brand{display:flex;justify-content:space-between;align-items:baseline;border-bottom:3px solid var(--coral);padding-bottom:10px;margin-bottom:6px;}
  header.brand .logo{font-weight:800;font-size:18pt;color:var(--navy);letter-spacing:1px;}
  header.brand .meta{font-size:8.5pt;color:var(--grey);}
  h1.title{font-size:24pt;color:var(--navy);font-weight:800;margin:24px 0 0;line-height:1.05;}
  h1.title .accent{color:var(--coral);display:block;}
  .lead{text-align:justify;margin:14px 0;}
  .party{font-weight:700;color:var(--navy);}
  .andword{font-style:italic;}
  h2.section{font-size:13pt;color:var(--navy);font-weight:700;margin:24px 0 8px;}
  p{text-align:justify;margin:8px 0;}
  .sub{font-weight:700;color:var(--navy);}
  ul.dash{list-style:none;margin:6px 0 10px;padding-left:24px;}
  ul.dash li{position:relative;padding-left:18px;margin:3px 0;text-align:justify;}
  ul.dash li::before{content:"\2013";color:var(--coral);position:absolute;left:0;font-weight:700;}
  .label{font-size:9pt;font-weight:700;color:var(--navy);text-transform:uppercase;letter-spacing:.5px;margin:16px 0 8px;}
  table.details{width:100%;border-collapse:collapse;margin:8px 0 4px;}
  table.details td{border:1px solid var(--line);padding:8px 12px;font-size:10pt;vertical-align:top;}
  table.details td.k{background:var(--light);font-weight:700;color:var(--navy);width:32%;}
  table.details td.v{height:14px;}
  .callout{background:var(--light);border-left:4px solid var(--coral);padding:12px 16px;margin:14px 0;font-size:10pt;}
  .execution{page-break-before:always;}
  h2.exec{font-size:18pt;color:var(--navy);font-weight:800;margin:8px 0 14px;}
  .sigwrap{display:flex;gap:0;border:1px solid var(--line);}
  .sigcell{flex:1;padding:16px;}
  .sigcell + .sigcell{border-left:1px solid var(--line);}
  .sigcell .h{font-weight:700;color:var(--navy);font-size:10.5pt;margin-bottom:4px;}
  .sigcell .org{font-size:10pt;margin:2px 0;}
  .sigline{border-bottom:1.5px solid var(--navy);height:34px;margin-top:14px;}
  .sigcap{font-size:8.5pt;color:var(--grey);margin-top:2px;}
  footer.foot{border-top:1px solid var(--line);margin-top:40px;padding-top:8px;display:flex;justify-content:space-between;font-size:8.5pt;color:var(--grey);}
  @media print{body{background:#fff;}.page{box-shadow:none;margin:0;max-width:100%;padding:0 12mm;}@page{size:A4;margin:14mm 0;}}</style>
<div class="page"><header class="brand"><div class="logo">FIXFY</div><div class="meta">Getfixfy Ltd &middot; Co. No. 15406523</div></header>
  <h1 class="title">SELF-BILLING<span class="accent">AGREEMENT</span></h1>
  <p class="lead">This Self-Billing Agreement (the &ldquo;Agreement&rdquo;) is made between <span class="party">GETFIXFY LTD</span>, a company incorporated in England and Wales under company number 15406523, registered office 124 City Road, London EC1V 2NX (the &ldquo;Self-Biller&rdquo; or &ldquo;Fixfy&rdquo;), and the undersigned Partner (the &ldquo;Supplier&rdquo;).</p>
  <p class="lead">It sets out the terms on which Fixfy will issue self-billed invoices on behalf of the Supplier for Jobs completed through the Fixfy platform, in accordance with HMRC self-billing requirements.</p>

  <div class="callout"><strong>What self-billing means.</strong> Under a self-billing arrangement, the customer (Fixfy) prepares the supplier&rsquo;s invoice and sends a copy to the supplier with the payment. The Supplier agrees not to raise its own sales invoices for the transactions covered by this Agreement.</div>

  <div class="label">Supplier Details</div>
  <table class="details">
    <tr><td class="k">Full legal / Trading name</td><td class="v"></td></tr>
    <tr><td class="k">Business address</td><td class="v"></td></tr>
    <tr><td class="k">Company / UTR number (if any)</td><td class="v"></td></tr>
    <tr><td class="k">VAT registration number (if VAT registered)</td><td class="v"></td></tr>
    <tr><td class="k">Email</td><td class="v"></td></tr>
  </table>

  <h2 class="section">1.&nbsp;&nbsp;Agreement to Self-Bill</h2>
  <p><span class="sub">1.1</span>&nbsp;&nbsp;The Supplier agrees that Fixfy may issue self-billed invoices for all Jobs completed by the Supplier through the platform for the duration of this Agreement.</p>
  <p><span class="sub">1.2</span>&nbsp;&nbsp;The Supplier agrees not to raise sales invoices for the supplies covered by this Agreement.</p>
  <p><span class="sub">1.3</span>&nbsp;&nbsp;This Agreement takes effect on the date of acceptance and remains in force for a period of twelve (12) months, automatically renewing for successive twelve-month periods unless terminated earlier in accordance with clause 5.</p>

  <h2 class="section">2.&nbsp;&nbsp;Supplier Obligations</h2>
  <p>The Supplier agrees to:</p>
  <ul class="dash">
    <li>accept self-billed invoices raised by Fixfy on the Supplier&rsquo;s behalf until this Agreement ends;</li>
    <li>notify Fixfy immediately if the Supplier changes its VAT registration number;</li>
    <li>notify Fixfy immediately if the Supplier becomes, or ceases to be, registered for VAT;</li>
    <li>notify Fixfy immediately if the Supplier transfers its business, or part of it, as a going concern;</li>
    <li>not issue its own VAT or sales invoices for the supplies covered by this Agreement; and</li>
    <li>keep copies of all self-billed invoices it receives.</li>
  </ul>

  <h2 class="section">3.&nbsp;&nbsp;Fixfy Obligations</h2>
  <p>Fixfy agrees to:</p>
  <ul class="dash">
    <li>issue self-billed invoices showing the Supplier&rsquo;s name, address and, where applicable, VAT registration number, together with all particulars required for a valid VAT invoice;</li>
    <li>include on each self-billed invoice the statement &ldquo;The VAT shown is your output tax due to HMRC&rdquo; where the Supplier is VAT registered;</li>
    <li>issue a new self-billing agreement if the Supplier&rsquo;s VAT registration number changes;</li>
    <li>send a copy of each self-billed invoice to the Supplier and retain a copy; and</li>
    <li>not reclaim input tax on invoices that are incorrect or where this Agreement has ended.</li>
  </ul>

  <h2 class="section">4.&nbsp;&nbsp;VAT and the Agency Model</h2>
  <p><span class="sub">4.1</span>&nbsp;&nbsp;Fixfy acts as a disclosed agent introducing Jobs between Clients and the Supplier. The Supplier supplies its Services to the Client; Fixfy provides agency, coordination and platform services and charges commission.</p>
  <p><span class="sub">4.2</span>&nbsp;&nbsp;Where the Supplier is VAT registered, the self-billed invoice will reflect the VAT due on the Supplier&rsquo;s supply. Fixfy&rsquo;s commission is accounted for separately, with VAT applied to the commission as required by law.</p>
  <p><span class="sub">4.3</span>&nbsp;&nbsp;The Supplier is solely responsible for accounting to HMRC for any VAT and income tax due on its supplies.</p>

  <h2 class="section">5.&nbsp;&nbsp;Duration and Termination</h2>
  <p><span class="sub">5.1</span>&nbsp;&nbsp;Either party may terminate this Agreement at any time by written notice (including through the platform).</p>
  <p><span class="sub">5.2</span>&nbsp;&nbsp;This Agreement automatically ends if the Supplier&rsquo;s circumstances change such that self-billing is no longer permitted under HMRC rules, including a change of VAT registration number until a new agreement is made.</p>
  <p><span class="sub">5.3</span>&nbsp;&nbsp;On termination, the Supplier resumes responsibility for issuing its own invoices for subsequent supplies.</p>

  <h2 class="section">6.&nbsp;&nbsp;Governing Law</h2>
  <p><span class="sub">6.1</span>&nbsp;&nbsp;This Agreement is governed by the laws of England and Wales and operated in accordance with HMRC self-billing requirements (VAT Notice 700/62 as amended from time to time).</p>

  <div class="execution">
    <h2 class="exec">ACCEPTANCE</h2>
    <p>By clicking &ldquo;Sign&rdquo; / &ldquo;Accept&rdquo; in the Fixfy onboarding portal, or by signing below, the Supplier agrees to this Self-Billing Agreement and confirms the Supplier Details above are correct.</p>
    <div class="sigwrap">
      <div class="sigcell">
        <div class="h">GETFIXFY LTD (Self-Biller)</div>
        <div class="org">Getfixfy Ltd</div>
        <div class="org">124 City Road, London EC1V 2NX</div>
        <div class="org">Co. No. 15406523</div>
        <div class="sigline"></div><div class="sigcap">Authorised signatory</div>
        <div class="sigline"></div><div class="sigcap">Date</div>
      </div>
      <div class="sigcell">
        <div class="h">THE SUPPLIER (Partner)</div>
        <div class="org">&nbsp;</div>
        <div class="sigline"></div><div class="sigcap">Name / Business name</div>
        <div class="sigline"></div><div class="sigcap">Signature</div>
        <div class="sigline"></div><div class="sigcap">Date</div>
      </div>
    </div>
  </div>

  <footer class="foot"><span>Self-Billing Agreement &middot; v2026 &mdash; Confidential</span><span>Getfixfy Ltd</span></footer></div>',
  true
);

-- Contractor Service Agreement
UPDATE public.contract_versions SET is_active = false WHERE contract_type = 'contractor_service_agreement' AND is_active = true;
INSERT INTO public.contract_versions (contract_type, version, title, body_html, is_active)
VALUES (
  'contractor_service_agreement',
  '2026-06-09',
  'Contractor Service Agreement',
  '<style>:root{--navy:#020040;--coral:#ED4B00;--ink:#1a1a1a;--grey:#555;--light:#f2f2f5;--line:#ccc;}
  *{box-sizing:border-box;}
  html{-webkit-print-color-adjust:exact;print-color-adjust:exact;}
  body{font-family:Arial,Helvetica,sans-serif;color:var(--ink);background:#e9e9ee;margin:0;line-height:1.5;font-size:11pt;}
  .page{background:#fff;max-width:820px;margin:24px auto;padding:48px 56px 64px;box-shadow:0 2px 16px rgba(0,0,0,.12);}
  header.brand{display:flex;justify-content:space-between;align-items:baseline;border-bottom:3px solid var(--coral);padding-bottom:10px;margin-bottom:6px;}
  header.brand .logo{font-weight:800;font-size:18pt;color:var(--navy);letter-spacing:1px;}
  header.brand .meta{font-size:8.5pt;color:var(--grey);}
  h1.title{font-size:24pt;color:var(--navy);font-weight:800;margin:24px 0 0;line-height:1.05;}
  h1.title .accent{color:var(--coral);display:block;}
  .lead{text-align:justify;margin:14px 0;}
  .party{font-weight:700;color:var(--navy);}
  .andword{font-style:italic;}
  h2.section{font-size:13pt;color:var(--navy);font-weight:700;margin:24px 0 8px;}
  p{text-align:justify;margin:8px 0;}
  .sub{font-weight:700;color:var(--navy);}
  ul.dash{list-style:none;margin:6px 0 10px;padding-left:24px;}
  ul.dash li{position:relative;padding-left:18px;margin:3px 0;text-align:justify;}
  ul.dash li::before{content:"\2013";color:var(--coral);position:absolute;left:0;font-weight:700;}
  .label{font-size:9pt;font-weight:700;color:var(--navy);text-transform:uppercase;letter-spacing:.5px;margin:16px 0 8px;}
  table.details{width:100%;border-collapse:collapse;margin:8px 0 4px;}
  table.details td{border:1px solid var(--line);padding:8px 12px;font-size:10pt;vertical-align:top;}
  table.details td.k{background:var(--light);font-weight:700;color:var(--navy);width:32%;}
  table.details td.v{height:14px;}
  .callout{background:var(--light);border-left:4px solid var(--coral);padding:12px 16px;margin:14px 0;font-size:10pt;}
  .execution{page-break-before:always;}
  h2.exec{font-size:18pt;color:var(--navy);font-weight:800;margin:8px 0 14px;}
  .sigwrap{display:flex;gap:0;border:1px solid var(--line);}
  .sigcell{flex:1;padding:16px;}
  .sigcell + .sigcell{border-left:1px solid var(--line);}
  .sigcell .h{font-weight:700;color:var(--navy);font-size:10.5pt;margin-bottom:4px;}
  .sigcell .org{font-size:10pt;margin:2px 0;}
  .sigline{border-bottom:1.5px solid var(--navy);height:34px;margin-top:14px;}
  .sigcap{font-size:8.5pt;color:var(--grey);margin-top:2px;}
  footer.foot{border-top:1px solid var(--line);margin-top:40px;padding-top:8px;display:flex;justify-content:space-between;font-size:8.5pt;color:var(--grey);}
  @media print{body{background:#fff;}.page{box-shadow:none;margin:0;max-width:100%;padding:0 12mm;}@page{size:A4;margin:14mm 0;}}</style>
<div class="page"><header class="brand"><div class="logo">FIXFY</div><div class="meta">Getfixfy Ltd &middot; Co. No. 15406523</div></header>
  <h1 class="title">CONTRACTOR<span class="accent">SERVICE AGREEMENT</span></h1>
  <p class="lead">This Contractor Service Agreement (the &ldquo;Agreement&rdquo;) is made between <span class="party">GETFIXFY LTD</span>, a company incorporated in England and Wales under company number 15406523, registered office 124 City Road, London EC1V 2NX (&ldquo;Fixfy&rdquo; or the &ldquo;Company&rdquo;), and the undersigned independent contractor (the &ldquo;Contractor&rdquo;).</p>
  <p class="lead">It governs the terms on which the Contractor performs maintenance, repair and facilities Services for Clients introduced through the Fixfy platform.</p>

  <div class="callout"><strong>Relationship.</strong> The Contractor is an independent business engaged on a non-exclusive, job-by-job basis. Fixfy acts as a disclosed agent introducing Jobs; it is not the Contractor&rsquo;s employer and is not the end client of the works.</div>

  <div class="label">Contractor Details</div>
  <table class="details">
    <tr><td class="k">Full legal / Trading name</td><td class="v"></td></tr>
    <tr><td class="k">Registration / UTR / Company no.</td><td class="v"></td></tr>
    <tr><td class="k">Trade(s) and certifications held</td><td class="v"></td></tr>
    <tr><td class="k">Business address</td><td class="v"></td></tr>
    <tr><td class="k">Public liability insurance (insurer / cover)</td><td class="v"></td></tr>
    <tr><td class="k">Email</td><td class="v"></td></tr>
  </table>

  <h2 class="section">1.&nbsp;&nbsp;Services</h2>
  <p><span class="sub">1.1</span>&nbsp;&nbsp;The Contractor shall perform maintenance, repair, installation and related facilities Services for Jobs it accepts through the platform (the &ldquo;Services&rdquo;).</p>
  <p><span class="sub">1.2</span>&nbsp;&nbsp;Each accepted Job, together with its scope, location, pricing and timing, forms a specific engagement under this Agreement.</p>
  <p><span class="sub">1.3</span>&nbsp;&nbsp;The Contractor is free to accept or decline any Job and is under no obligation to accept a minimum volume of work.</p>

  <h2 class="section">2.&nbsp;&nbsp;Independent Business Status</h2>
  <p><span class="sub">2.1</span>&nbsp;&nbsp;The Contractor performs the Services as an independent business and not as an employee or worker of Fixfy. Nothing in this Agreement creates any employment, partnership, joint venture, or exclusivity.</p>
  <p><span class="sub">2.2</span>&nbsp;&nbsp;The Contractor controls how, when and by whom the Services are performed, subject to the Job requirements, agreed attendance windows and quality standards.</p>
  <p><span class="sub">2.3</span>&nbsp;&nbsp;The Contractor may send a suitably qualified and insured substitute to perform a Job, provided the substitute meets the same vetting, certification and standards requirements.</p>
  <p><span class="sub">2.4</span>&nbsp;&nbsp;The Contractor is responsible for its own taxes, National Insurance, VAT (where applicable), and obligations to its own personnel, and indemnifies Fixfy against any related claim.</p>

  <h2 class="section">3.&nbsp;&nbsp;Qualifications, Insurance and Compliance</h2>
  <p><span class="sub">3.1</span>&nbsp;&nbsp;The Contractor warrants that it holds and maintains all licences, qualifications, certifications and insurance required to perform the Services lawfully, including, where relevant, Gas Safe, NICEIC, NAPIT, EICR and Fire Safety certifications, and valid public liability insurance.</p>
  <p><span class="sub">3.2</span>&nbsp;&nbsp;The Contractor shall upload valid evidence to the platform and keep it current. Fixfy may suspend allocation of Jobs where evidence is expired, missing or unverifiable.</p>
  <p><span class="sub">3.3</span>&nbsp;&nbsp;The Contractor shall comply with all applicable law, health and safety requirements, and site rules when performing the Services.</p>

  <h2 class="section">4.&nbsp;&nbsp;Standards and Service Levels</h2>
  <p><span class="sub">4.1</span>&nbsp;&nbsp;The Contractor shall perform the Services with reasonable skill and care, to industry standard, and complete each Job to the scope agreed.</p>
  <p><span class="sub">4.2</span>&nbsp;&nbsp;The Contractor shall meet agreed response and attendance windows, communicate progress through the platform, and record completion as required.</p>
  <p><span class="sub">4.3</span>&nbsp;&nbsp;Defective or incomplete work shall be remedied by the Contractor at its own cost. Repeated failure to meet standards may result in reduced Job allocation, suspension or termination.</p>

  <h2 class="section">5.&nbsp;&nbsp;Fees, Commission and Payment</h2>
  <p><span class="sub">5.1</span>&nbsp;&nbsp;The fee for each Job is the amount shown or agreed on the platform for that Job. Fixfy applies its commission to each Job at the rate notified to the Contractor.</p>
  <p><span class="sub">5.2</span>&nbsp;&nbsp;All payments are processed through the platform&rsquo;s integrated payment system. The Contractor shall not take payment directly from the Client for platform Jobs.</p>
  <p><span class="sub">5.3</span>&nbsp;&nbsp;Invoicing is handled by self-billing under the separate Self-Billing Agreement. Fixfy issues a self-billed invoice and remits the Contractor&rsquo;s fee, net of commission, in accordance with the agreed payment cycle.</p>
  <p><span class="sub">5.4</span>&nbsp;&nbsp;Fixfy is responsible only for fees relating to Jobs effectively completed and recorded on the platform.</p>

  <h2 class="section">6.&nbsp;&nbsp;Anti-Circumvention</h2>
  <p><span class="sub">6.1</span>&nbsp;&nbsp;For any Client introduced through the platform, the Contractor shall not solicit, divert, accept or perform work for that Client outside the platform where the work originated through Fixfy, whether directly or indirectly.</p>
  <p><span class="sub">6.2</span>&nbsp;&nbsp;The Contractor shall not retain, share or use Client contact details to bypass the platform. Breach may result in immediate termination and recovery of lost commission.</p>

  <h2 class="section">7.&nbsp;&nbsp;Confidentiality and Data</h2>
  <p><span class="sub">7.1</span>&nbsp;&nbsp;The Contractor shall keep confidential all Client data, pricing, systems, workflows and commercial information of Fixfy, during and after this Agreement.</p>
  <p><span class="sub">7.2</span>&nbsp;&nbsp;Job history, documentation and records generated on the platform remain the property of Fixfy and the relevant Client. Both parties shall comply with the UK GDPR and the Data Protection Act 2018.</p>

  <h2 class="section">8.&nbsp;&nbsp;Liability and Indemnity</h2>
  <p><span class="sub">8.1</span>&nbsp;&nbsp;The Contractor is solely responsible for the Services it performs and indemnifies Fixfy and the Client against loss, damage or claims arising from the Contractor&rsquo;s acts, omissions, defective work or breach of this Agreement.</p>
  <p><span class="sub">8.2</span>&nbsp;&nbsp;Nothing in this Agreement excludes liability for death or personal injury caused by negligence, fraud, or any liability that cannot be excluded by law.</p>

  <h2 class="section">9.&nbsp;&nbsp;Term and Termination</h2>
  <p><span class="sub">9.1</span>&nbsp;&nbsp;This Agreement remains in force until terminated by either party on written notice (including through the platform).</p>
  <p><span class="sub">9.2</span>&nbsp;&nbsp;Fixfy may suspend or terminate immediately for breach, expired certifications, safety risk or conduct harmful to Clients or the platform.</p>
  <p><span class="sub">9.3</span>&nbsp;&nbsp;On termination the Contractor shall complete any Job already in progress (unless instructed otherwise), cease representing Fixfy, and return or delete Company and Client data. Clauses on confidentiality, anti-circumvention, data, liability and accrued payment survive termination.</p>

  <h2 class="section">10.&nbsp;&nbsp;Nature of the Relationship &mdash; Acknowledgements</h2>
  <p>The Contractor acknowledges that Job coordination, response windows, quality standards and platform communication requirements are commercial service requirements and shall not be interpreted as employment supervision, working-hour control or labour subordination.</p>

  <h2 class="section">11.&nbsp;&nbsp;Governing Law</h2>
  <p><span class="sub">11.1</span>&nbsp;&nbsp;This Agreement is governed by the laws of England and Wales. Disputes shall be subject to confidential arbitration in London under the LCIA Rules, with London as the seat and English as the language.</p>

  <div class="execution">
    <h2 class="exec">EXECUTION</h2>
    <p>By clicking &ldquo;Sign&rdquo; / &ldquo;Accept&rdquo; in the Fixfy onboarding portal, or by signing below, the parties agree to this Contractor Service Agreement.</p>
    <div class="sigwrap">
      <div class="sigcell">
        <div class="h">For and on behalf of GETFIXFY LTD</div>
        <div class="org">Getfixfy Ltd</div>
        <div class="org">124 City Road, London EC1V 2NX</div>
        <div class="org">Co. No. 15406523</div>
        <div class="sigline"></div><div class="sigcap">Authorised signatory</div>
        <div class="sigline"></div><div class="sigcap">Date</div>
      </div>
      <div class="sigcell">
        <div class="h">THE CONTRACTOR</div>
        <div class="org">(as identified in Contractor Details above)</div>
        <div class="sigline"></div><div class="sigcap">Name / Business name</div>
        <div class="sigline"></div><div class="sigcap">Signature</div>
        <div class="sigline"></div><div class="sigcap">Date</div>
      </div>
    </div>
  </div>

  <footer class="foot"><span>Contractor Service Agreement &middot; v2026 &mdash; Confidential</span><span>Getfixfy Ltd</span></footer></div>',
  true
);
