-- A régua de labour do orçamentista: o que o mercado do UK cobra por serviço.
--
-- Colhida ao vivo em 17/08/2026 dos guias de preço de referência (Checkatrade
-- cost guides, MyBuilder pricing guides, PriceYourJob, HouseholdQuotes,
-- hamuch, Rated People, TaskRabbit, Airtasker, e dois operadores fixos de
-- Londres como teto de mercado). 148 referências em 12 trades.
--
-- A regra de precificação que esta tabela serve (fixada pelo dono em 17/08):
--   · handyman é o ÚNICO serviço por tempo (hora / meia diária / diária, fixo);
--   · todo o resto é preço POR SERVIÇO, calibrado por estas referências;
--   · material entra sempre via supplier_prices com margem de 30%.
--
-- Cada linha é o que a FONTE disse, não o nosso preço: low/high/typical em £,
-- includes_materials quando a página declarou (null = não disse), e a nota de
-- Londres quando havia. O orçamentista lê o conjunto e tira o preço; linha
-- torta ficou fora na curadoria (ex.: laminado £40-£50/m2 "labour" que brigava
-- com três fontes em £6-£20 — está só no docs/labour-referencia, marcada).

create table if not exists labour_prices (
  id                 uuid primary key default gen_random_uuid(),
  trade              text not null,
  task               text not null,
  unit               text not null,
  low_gbp            numeric,
  high_gbp           numeric,
  typical_gbp        numeric,
  -- null = a fonte não declarou; o orçamentista trata como "provavelmente com material"
  includes_materials boolean,
  day_rate_gbp       numeric,
  london_note        text,
  source_url         text not null,
  fetched_at         timestamptz not null default now(),
  unique (trade, task)
);

create index if not exists labour_prices_trade_idx on labour_prices (trade);

insert into labour_prices (trade, task, unit, low_gbp, high_gbp, typical_gbp, includes_materials, day_rate_gbp, london_note, source_url) values
  ('carpenter', 'carpenter hourly rate (general/finish carpentry)', 'per_hour', 30, 45, 37.5, false, 300, 'London carpenter rates often 20-40% higher than UK average', 'https://www.checkatrade.com/blog/cost-guides/carpentry-prices-guide/'),
  ('carpenter', 'carpenter/joiner hourly rate, London', 'per_hour', 25, 60, 35, false, 230, 'London-specific page (1,538+ trades); day rate £150-£480, average £230; area averages £34-£38/hr', 'https://www.hamuch.com/rates/carpenter-joiner/london'),
  ('carpenter', 'hang internal door (labour only)', 'per_item', 100, 140, 120, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/carpentry-prices-guide/'),
  ('carpenter', 'hang internal door, budget labour-only (~£50/door, fitter hangs ~3 doors/day)', 'per_item', 50, 150, 120, false, 150, 'Day rates geographically varied, higher in London and surrounding areas', 'https://www.priceyourjob.co.uk/fit-internal-door-cost/'),
  ('carpenter', 'internal door supply and install (softwood £125-£350, hardwood £200-£400)', 'per_item', 125, 400, null, true, null, 'Labour-only component £75-£600 depending on complexity; labour rates higher in London and South East', 'https://www.checkatrade.com/blog/cost-guides/door-installation-costs/'),
  ('carpenter', 'fit fire door FD30 (fit-only; door supply £65-£600 extra; supply+fit from £300+)', 'per_item', 30, 50, null, false, 300, null, 'https://www.checkatrade.com/blog/cost-guides/fire-door-installation-cost/'),
  ('carpenter', 'install new front/external door (labour)', 'per_item', 500, 1000, null, false, null, 'uPVC front door installed £400-£1,000 incl glazing and architrave; wooden front door £550-£1,800', 'https://www.checkatrade.com/blog/cost-guides/door-installation-costs/'),
  ('carpenter', 'supply and fit skirting board', 'per_metre', 20, 40, 30, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/carpentry-prices-guide/'),
  ('carpenter', 'replace skirting boards, medium room (complex rooms to ~£800)', 'per_room', 300, 800, 400, true, null, 'London properties typically exceed national averages; labour £100-£175/day per person', 'https://www.priceyourjob.co.uk/replacing-skirting-boards-cost/'),
  ('carpenter', 'replace architrave, per door (whole house £500-£1,000)', 'per_door', 100, 100, 100, true, null, 'Regional job examples: London £290 vs Plymouth £238', 'https://www.hamuch.com/cost/new-skirting-architrave-coving'),
  ('carpenter', 'bespoke alcove cupboard and shelving (install quotes, materials extra)', 'per_job', 850, 1540, 1095, false, null, 'London tradesperson quotes; typical London carpenter £33-£38/hr, £223-£239/day', 'https://www.hamuch.com/cost/alcove-cupboard-shelves/london'),
  ('carpenter', 'construct built-in fitted wardrobe', 'per_item', 800, 1400, 1100, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/carpentry-prices-guide/'),
  ('carpenter', 'boxing in pipes (installation quotes)', 'per_job', 303, 763, 467, false, null, 'London quotes; Manchester from £243', 'https://www.hamuch.com/cost/box-in-pipes/london'),
  ('carpenter', 'loft hatch installation (widening +£50-£300; moving hatch £250-£725)', 'per_item', 150, 525, 240, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/loft-hatch-installation-cost/'),
  ('carpenter', 'stair banister/handrail replacement labour (typical fit ~3 hrs; worked example 4m staircase £945 incl materials)', 'per_hour', 60, 80, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/cost-new-banister-spindles/'),
  ('flooring', 'laminate fitting labour (basic £6-£10, luxury £12-£20)', 'per_m2', 6, 20, null, false, null, 'London & South East labour £12-£18 per m2 vs Midlands £7-£10', 'https://www.mybuilder.com/carpets-lino-flooring/price-guides/laminate-floor-fitter-cost'),
  ('flooring', 'laminate fitting labour only', 'per_m2', 10, 12, null, false, 150, null, 'https://www.priceyourjob.co.uk/install-laminate-flooring-cost/'),
  ('flooring', 'laminate supply and fit (underlay £2-£5/m2 extra)', 'per_m2', 15, 27, null, true, null, null, 'https://www.priceyourjob.co.uk/install-laminate-flooring-cost/'),
  ('flooring', 'laminate flooring with installation (supply and fit)', 'per_m2', 22, 40, null, true, null, null, 'https://www.ratedpeople.com/blog/flooring-prices-carpet-laminate-and-wood-costs-per-m2'),
  ('flooring', 'LVT/luxury vinyl tile supply and fit (fitting labour component £10-£20/m2; subfloor prep £5-£15/m2 extra)', 'per_m2', 20, 60, null, true, null, null, 'https://www.mybuilder.com/carpets-lino-flooring/price-guides/lvt-flooring-cost'),
  ('flooring', 'engineered wood flooring install, labour only (solid wood £50-£60/m2, herringbone £65-£90/m2)', 'per_m2', 45, 55, 50, false, null, 'London carpenter rates often 20-40% higher', 'https://www.checkatrade.com/blog/cost-guides/carpentry-prices-guide/'),
  ('flooring', 'carpet fitting labour day rate (hourly £20-£35; standard room incl carpet £100-£500)', 'per_day', 150, 250, null, false, null, 'Big cities and difficult-access properties incur higher labour charges', 'https://www.checkatrade.com/blog/cost-guides/carpet-fitting-cost/'),
  ('flooring', 'carpet underlay supply and fit', 'per_m2', 8, 12, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/carpet-fitting-cost/'),
  ('flooring', 'floor sanding and refinishing (sanding only £13-£15/m2; sand+varnish £16-£19/m2; 20m2 room £500-£600)', 'per_m2', 25, 30, null, null, null, 'London specialists £34-£40/hr, above national average; specialist day rate £100-£220', 'https://www.priceyourjob.co.uk/restoring-wood-flooring-cost/'),
  ('flooring', 'trim/adjust door after new flooring', 'per_door', 20, 30, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/carpet-fitting-cost/'),
  ('flooring', 'flooring specialist hourly rate (laminate ~£240/day, wooden flooring ~£250/day, carpet ~£22/hr or £150/day)', 'per_hour', 25, 50, 30, false, 240, 'London £36/hr and £232/day', 'https://www.hamuch.com/rates/flooring'),
  ('handyman', 'hourly rate (UK average)', 'per_hour', 30, 60, 30, false, null, 'UK average; same guide cites ~£50/hr in London', 'https://www.checkatrade.com/blog/cost-guides/handyman-prices/'),
  ('handyman', 'hourly rate (UK average, 2026 data)', 'per_hour', 10, 45, 27, false, 188, 'UK average', 'https://www.hamuch.com/rates/handyman'),
  ('handyman', 'hourly rate (London)', 'per_hour', 33, 80, 38, false, 240, 'London-specific; most cluster £34-£40/hr', 'https://www.hamuch.com/rates/handyman/london'),
  ('handyman', 'hourly rate (London, TaskRabbit; avg invoice £119, UK avg £33/hr on same page)', 'per_hour', null, null, 51, false, null, 'London-specific; fixed-per-task platform, priced hourly', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'day rate (UK average)', 'per_day', 115, 125, 120, false, 120, 'UK average', 'https://www.priceyourjob.co.uk/handyman-prices/'),
  ('handyman', 'day rate (London)', 'per_day', 180, 270, 225, false, 225, 'London-specific; first hour £50-£60 then ~£25 per half hour', 'https://www.priceyourjob.co.uk/handyman-prices/'),
  ('handyman', 'half-day rate, up to 4h (London premium fixed-price firm; full day £500-£650, hourly £80-£100)', 'per_half_day', 280, 380, 330, false, null, 'London-specific; top end of market', 'https://londonhandymanpro.co.uk/handyman-prices-london/'),
  ('handyman', 'minimum call-out charge (typical small-job visit averages £80)', 'per_job', 40, 50, 45, false, null, 'UK norm', 'https://www.checkatrade.com/blog/cost-guides/handyman-prices/'),
  ('handyman', 'call-out norm London operator: £60+VAT first 30 min (£72 inc VAT), then £30+VAT per 30 min', 'per_job', 60, 72, 72, false, null, 'London-specific (Silver Saints)', 'https://www.silversaints.com/our-rates/'),
  ('handyman', 'TV wall mounting by size: <32in 60-120, 32-43in 80-150, 43-55in 100-180, 55-65in 130-220, 65in+ 180-300 (London £48/hr vs UK £35/hr)', 'per_job', 60, 300, 140, false, null, 'UK ranges; updated Aug 2026', 'https://www.taskrabbit.co.uk/cost-guides/wall-mount-tv'),
  ('handyman', 'TV wall mounting (Central London typical job; UK-wide range £50-£250, median £150)', 'per_job', 50, 100, 70, false, null, 'London-specific median £70; task-marketplace fixed pricing', 'https://www.airtasker.com/uk/costs/tv-wall-mounting/tv-wall-mounting-cost/'),
  ('handyman', 'flat-pack assembly: two-door wardrobe (70-100 min)', 'per_item', 45, 60, 50, false, null, 'UK average; London above-average per same guide', 'https://www.priceyourjob.co.uk/furniture-assembly-cost/'),
  ('handyman', 'flat-pack assembly: 4-door or sliding-door wardrobe, PAX-style (2-4h); first hour £25-£60, avg £40', 'per_item', 70, 130, 100, false, null, 'UK average', 'https://www.priceyourjob.co.uk/furniture-assembly-cost/'),
  ('handyman', 'flat-pack furniture assembly, single item', 'per_item', 40, 80, 60, false, null, 'UK range', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'hanging pictures / shelves', 'per_job', 40, 70, 55, false, null, 'UK range; London firm quotes £45-£90 picture/mirror, £45-£75 floating shelf (londonhandymanpro.co.uk)', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'fitting blind or curtain rail/pole (per window)', 'per_job', 50, 90, 70, false, null, 'UK range; London fixed prices £40-£60 blind, £50-£90 pole (londonhandymanpro.co.uk)', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'fixing/easing a sticking door', 'per_job', 50, 90, 70, false, null, 'UK range', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'replacing door handle or lock', 'per_job', 50, 100, 75, false, null, 'UK range', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'replace euro cylinder lock/barrel supply+fit (£100 typical; overall lock change avg £125-£150; labour £50 first hour)', 'per_job', 100, 150, 100, true, null, 'UK average', 'https://www.priceyourjob.co.uk/door-lock-replacement-cost/'),
  ('handyman', 'draught proofing, per standard window (~£50); external door incl letterbox/keyhole ~£100', 'per_window', 50, 100, 50, true, null, 'UK average', 'https://www.checkatrade.com/blog/cost-guides/draught-proofing-cost/'),
  ('handyman', 're-sealing/grouting bath or shower (mastic/silicone)', 'per_job', 80, 150, 115, true, null, 'UK range; London fixed price £110+VAT (silversaints.com)', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'gutter cleaning (terraced £100, semi £125, detached £150; half-day job, no scaffold)', 'per_job', 100, 150, 125, false, null, 'UK average', 'https://www.priceyourjob.co.uk/gutter-cleaning-cost/'),
  ('handyman', 'patching/filling small wall area (small plaster patch)', 'per_job', 60, 120, 90, false, null, 'UK range', 'https://www.taskrabbit.co.uk/blog/handyman-cost-guide-united-kingdom/'),
  ('handyman', 'bleeding radiators (visit)', 'per_job', 60, 90, 75, false, null, 'UK range', 'https://nationalplumbingservices.co.uk/radiator-repair-costs-in-the-uk/'),
  ('handyman', 'garden odd jobs / maintenance (hamuch cites £50 for 2h lawn mowing/weeding)', 'per_hour', 15, 30, 22, false, null, 'UK average', 'https://www.priceyourjob.co.uk/handyman-prices/'),
  ('painter', 'day rate', 'per_day', 250, 400, 325, false, 325, 'page notes London and major-city day rates tend to be higher (no % given)', 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'day rate (marketplace average)', 'per_day', 127, 271, 173, false, 173, 'London average £203/day vs £173 UK (~+17%)', 'https://www.hamuch.com/rates/painter-decorator'),
  ('painter', 'hourly rate', 'per_hour', 16, 38, 24, false, 173, 'London average £31/hr vs £24 UK (~+29%); London range £20-£60/hr per https://www.hamuch.com/rates/painter-decorator/london', 'https://www.hamuch.com/rates/painter-decorator'),
  ('painter', 'hourly rate (labour only)', 'per_hour', 15, 40, null, false, null, 'labour up to +20% in London and the South East; £20-£50/hr if materials included', 'https://www.ratedpeople.com/blog/how-much-does-a-painter-and-decorator-cost-in-2025'),
  ('painter', 'paint small room (8m2, walls+ceiling)', 'per_room', null, null, 350, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint medium room (18m2, walls+ceiling)', 'per_room', null, null, 450, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint large room (30m2, walls+ceiling)', 'per_room', null, null, 1000, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint standard bedroom/living room (walls+ceiling, two coats)', 'per_room', 300, 500, null, null, null, null, 'https://www.mybuilder.com/painting-decorating/price-guides/painting-a-room-cost'),
  ('painter', 'paint single room, walls only (prep + two coats emulsion)', 'per_room', 250, 300, 250, true, null, 'London much higher than e.g. Newcastle (no % given); ~£200 labour + £50 materials', 'https://www.priceyourjob.co.uk/painting-interior-walls-cost/'),
  ('painter', 'paint medium room / bedroom (100-200 sq ft)', 'per_room', 450, 950, null, true, null, 'labour up to +20% in London and the South East', 'https://www.ratedpeople.com/blog/how-much-does-a-painter-and-decorator-cost-in-2025'),
  ('painter', 'paint ceiling only', 'per_m2', 10, 20, 15, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint interior door (both sides)', 'per_door', 80, 100, 90, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint skirting boards, average room (3m x 3m)', 'per_room', 200, 300, 200, true, null, 'London most expensive area for decorators (no % given); ~£150 labour + £50 materials; £300 if woodwork needs filling', 'https://www.priceyourjob.co.uk/painting-skirting-boards-cost/'),
  ('painter', 'woodwork add-on per room (skirting, architraves, door/window frames)', 'per_room', 50, 100, null, null, null, null, 'https://www.mybuilder.com/painting-decorating/price-guides/painting-a-room-cost'),
  ('painter', 'mist coat on new plaster', 'per_room', 80, 150, null, true, null, null, 'https://www.mybuilder.com/painting-decorating/price-guides/painting-a-room-cost'),
  ('painter', 'full repaint 2-bed flat (interior)', 'per_flat', 1500, 2500, 2000, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint hallway, stairs and landing (staircase area)', 'per_job', 1450, 1750, 1600, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'exterior painting, full 3-bed semi-detached house', 'per_job', 1100, 1500, 1300, true, null, '4-bed detached £1,750-£2,500 (typ £2,000); exterior rate £15-£25/m2 on same page', 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'wallpaper a room (4.4m x 3.3m), hanging labour only', 'per_room', 350, 500, 450, false, null, '£12-£16/m2 (typ £14) labour only, excludes wallpaper; cross-ref: hang-only medium room £200 labour, strip+hang £350 labour per https://www.priceyourjob.co.uk/wallpaper-room-cost/', 'https://www.checkatrade.com/blog/cost-guides/painter-decorator-prices/'),
  ('painter', 'paint front door', 'per_job', null, null, 351, null, null, null, 'https://www.hamuch.com/rates/painter-decorator'),
  ('paving', 'patio installation (all materials, supply+fit, UK average)', 'per_m2', 65, 475, 130, true, 280, null, 'https://www.checkatrade.com/blog/cost-guides/patio-laying-cost/'),
  ('paving', 'patio slab laying (labour-only, laying slabs and nothing else)', 'per_m2', 35, 100, null, false, 280, null, 'https://www.checkatrade.com/blog/cost-guides/patio-laying-cost/'),
  ('paving', 'patio installation (porcelain, materials only; landscaper labour £110-£180/day extra)', 'per_m2', 40, 80, 55, true, null, null, 'https://www.priceyourjob.co.uk/patio-laying-cost/'),
  ('paving', 'patio installation (indian sandstone / natural stone, materials only; two-person team £200-£300/day extra)', 'per_m2', 40, 90, 70, true, null, null, 'https://www.priceyourjob.co.uk/patio-laying-cost/'),
  ('paving', 'block paving driveway (supply+fit, UK average; 30m2 2-car drive approx £3,000)', 'per_m2', null, null, 100, true, null, null, 'https://householdquotes.co.uk/the-cost-block-paving'),
  ('paving', 'block paving / driveway installation (labour-only)', 'per_m2', 30, 50, null, false, 250, 'labour rates vary widely by UK area; average block paving cost also quoted at £100/m2 supply+fit', 'https://www.checkatrade.com/blog/cost-guides/block-paving-cost/'),
  ('paving', 'resin bound driveway (supply+fit; approx £70/m2 install plus approx £70/m2 if new sub-base needed; labour-only under £15/m2)', 'per_m2', 60, 120, 70, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/resin-bound-driveway-cost/'),
  ('paving', 'repointing a patio (resin/polymeric mortar, includes clean and refill)', 'per_m2', 10, 20, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/repointing-cost/'),
  ('paving', 'pressure washing patio (clean+seal slabs approx £6.50/m2; min call-out often based on 30m2)', 'per_m2', 3, 4.5, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/patio-cleaning-cost/'),
  ('paving', 'pressure washing driveway (typical job £250-£400, medium drive approx £350; wash+seal approx £700)', 'per_m2', 8.5, 15.5, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/cost-to-clean-a-driveway/'),
  ('fencing', 'fence installation (labour-only, standard panel; installers cover 10-15 panels/day)', 'per_panel', 40, 60, null, false, null, 'in London and the South East expect day rates at the upper end of £300-£400/day', 'https://www.mybuilder.com/fencing/price-guides/fence-panels-cost'),
  ('fencing', 'fence installation (labour-only)', 'per_m', 15, 30, null, false, null, null, 'https://www.mybuilder.com/pricing-guides/fencing-costs'),
  ('fencing', 'wooden fence, 8 panels / 15m garden (supply+fit; labour portion £1,000-£1,400)', 'per_job', 1825, 2515, null, true, null, null, 'https://www.priceyourjob.co.uk/installing-fence-panels-cost/'),
  ('fencing', 'new fence installation (whole job, all styles/lengths)', 'per_job', 1000, 5200, null, true, null, 'labour costs rise in London and the South East by as much as 20% on average', 'https://www.ratedpeople.com/blog/how-much-does-a-new-fence-installation-cost-in-2024'),
  ('fencing', 'fence post replacement (8ft timber post £50-£70, concrete £50-£80; replacing a rotted timber post approx £150 fitted; fence repair £60-£180/m incl labour)', 'per_post', 50, 150, 150, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/fence-repair-cost/'),
  ('fencing', 'gate installation (metal garden gate £175; wooden garden gate with concreted posts £400; pair of wooden driveway gates £750, supply+fit)', 'per_job', 175, 750, 400, true, 150, null, 'https://www.priceyourjob.co.uk/hang-gate-cost/'),
  ('decking', 'garden decking, softwood (supply+fit; labour £260-£340/day, 1-2 days typical)', 'per_m2', 70, 90, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/garden-decking-cost-guide/'),
  ('decking', 'garden decking, composite (supply+fit)', 'per_m2', 90, 110, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/garden-decking-cost-guide/'),
  ('decking', 'decking installation (labour-only, excl materials; ground-level at lower end, raised/steps higher)', 'per_m2', 20, 50, null, false, null, null, 'https://www.mybuilder.com/carpentry-joinery/price-guides/decking-cost'),
  ('garden', 'turf laying (labour-only; turf itself approx £5/m2 extra, levelling approx £20/m2 extra)', 'per_m2', 10, 30, 20, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/turfing-costs/'),
  ('garden', 'artificial grass (supply+fit all-in, incl excavation and sub-base)', 'per_m2', 45, 80, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/artificial-grass-cost/'),
  ('garden', 'garden clearance (per load; £45-£60/hr also quoted, avg £52.50/hr; typical domestic garden approx £300, overgrown avg £185)', 'per_load', 60, 360, 210, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/garden-clearance-cost/'),
  ('garden', 'landscaper day rate, London (avg £36/hr)', 'per_day', 223, 400, 240, false, 240, 'hamuch London average £240/day vs UK average £216/day (UK range £164-£324); most London contractors £35-£37/hr', 'https://www.hamuch.com/rates/landscaper/london'),
  ('plumber', 'hourly rate (UK average)', 'per_hour', 40, 60, 50, false, 350, null, 'https://www.checkatrade.com/blog/cost-guides/plumber-cost/'),
  ('plumber', 'hourly rate (London)', 'per_hour', 45, 105, 56, false, null, 'London average £56/hr; most listed plumbers £50-£70/hr; London day rates £250-£760', 'https://www.hamuch.com/rates/plumber/london'),
  ('plumber', 'day rate (UK average)', 'per_day', 150, 270, null, false, null, 'London day rate £200-£300+; London & South East hourly £60-£130 vs £25-£60 elsewhere', 'https://www.priceyourjob.co.uk/plumber-prices/'),
  ('plumber', 'emergency call-out fee (standard call-out £40-£60; out-of-hours charged 2.5-3x standard)', 'per_callout', 100, 180, null, false, null, null, 'https://www.priceyourjob.co.uk/emergency-plumbing-cost/'),
  ('plumber', 'replace kitchen/basin tap (fit only)', 'per_item', null, null, 140, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/tap-installation-cost/'),
  ('plumber', 'replace toilet (fit only; like-for-like from £150, wall-hung from £300, old toilet disposal ~£75)', 'per_item', 150, 300, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/toilet-installation-cost/'),
  ('plumber', 'replace toilet syphon/flush mechanism (supply & fit; repair labour ~£65/hr)', 'per_item', 60, 110, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/replace-toilet-syphon-cost/'),
  ('plumber', 'replace radiator (labour only, like-for-like swap)', 'per_item', 150, 300, 200, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/cost-remove-replace-radiator/'),
  ('plumber', 'replace radiator like-for-like (labour only; TRVs/balancing +£40-£80 per radiator)', 'per_item', 150, 300, null, false, null, null, 'https://www.ratedpeople.com/local-radiator'),
  ('plumber', 'unblock toilet', 'per_item', 75, 150, 112.5, true, null, 'expect to pay more in cities such as London', 'https://www.checkatrade.com/blog/cost-guides/cost-unblocking-toilet/'),
  ('plumber', 'unblock sink/toilet/drain', 'per_item', 75, 200, null, true, null, null, 'https://www.priceyourjob.co.uk/plumber-prices/'),
  ('plumber', 'unblock external drain (rodding avg £85; jetting avg £185)', 'per_item', 85, 185, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/drain-unblocking-cost/'),
  ('plumber', 'install dishwasher/washing machine (connect to existing plumbing; complex reroutes £100+)', 'per_item', 40, 90, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/dishwasher-installation-cost/'),
  ('plumber', 'replace bar mixer shower (labour only; unit itself ~£200 extra; full shower supply+install £300-£1,500)', 'per_item', null, null, 200, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/shower-installation-cost/'),
  ('plumber', 'outside tap installation (cold supply)', 'per_item', 120, 200, null, true, null, 'costs in London & South East tend to be slightly higher', 'https://www.checkatrade.com/blog/cost-guides/tap-installation-cost/'),
  ('plumber', 'outdoor tap replacement', 'per_item', 40, 120, null, true, null, null, 'https://www.mybuilder.com/plumbing/price-guides/outdoor-tap-replacement-cost'),
  ('plumber', 'reseal bath (remove old silicone, supply & apply new sealant, 60-90 min)', 'per_item', 50, 100, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/reseal-bath-cost/'),
  ('electrician', 'hourly rate (UK average)', 'per_hour', 35, 55, 40, false, null, 'London & South East ~£55/hr vs ~£35/hr in northern small towns; day rate £150-£280', 'https://www.priceyourjob.co.uk/electrician-prices/'),
  ('electrician', 'day rate (UK average; hourly £30-£45)', 'per_day', 250, 320, null, false, null, null, 'https://householdquotes.co.uk/electrician-prices-list'),
  ('electrician', 'hourly rate (London)', 'per_hour', 20, 100, 47, false, null, 'London average £47/hr; nearby London areas £48-£49/hr with day rates £274-£283; London day rates range £150-£800', 'https://www.hamuch.com/rates/electrician/london'),
  ('electrician', 'emergency electrician (urgent call-outs; minimum call-out fees common)', 'per_hour', 80, 100, 90, false, null, 'rates usually higher in London and major cities', 'https://www.checkatrade.com/blog/cost-guides/electrician-hourly-rate/'),
  ('electrician', 'replace socket/switch like-for-like (no relocation)', 'per_item', null, null, 75, true, null, null, 'https://www.priceyourjob.co.uk/electrician-prices/'),
  ('electrician', 'install new plug socket (adding sockets £55-£75 per socket incl basic materials; outdoor socket £130-£200+)', 'per_item', 100, 200, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/adding-plug-socket-room-cost/'),
  ('electrician', 'replace light fitting/pendant on existing ceiling rose (labour, at £45-£60/hr)', 'per_item', 55, 75, null, false, null, null, 'https://www.checkatrade.com/blog/how-to/replace-a-light-fixture/'),
  ('electrician', 'install wired outdoor security light (labour; fixture £20-£250 extra)', 'per_item', 100, 175, 150, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/cost-install-exterior-lights/'),
  ('electrician', 'EICR / electrical safety certificate (1-bed flat from £125; 5-bed detached up to £300+)', 'per_item', 125, 300, null, true, null, 'London & South East cost more per hour and per day than elsewhere', 'https://www.priceyourjob.co.uk/electrical-safety-certificate-cost/'),
  ('electrician', 'EICR certificate (UK avg £212; 3-bed house £200-£250; older pre-1990s wiring +25-35%)', 'per_item', 100, 300, 212, true, null, 'London & South East typically +15-20%', 'https://www.mybuilder.com/electrical/price-guides/eicr-certificate-cost'),
  ('electrician', 'consumer unit / fuse box replacement (10-way RCBO ~£485; 4-7 hours)', 'per_item', 450, 800, 485, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/cost-replacing-fuse-box-consumer-unit/'),
  ('electrician', 'mains smoke alarm installation (system supply & fit)', 'per_item', 150, 250, null, true, null, null, 'https://www.mybuilder.com/electrical/price-guides/smoke-alarm-installation-cost'),
  ('electrician', 'electric shower installation (standard supply & fit ~£400; 2-4 hours)', 'per_item', 300, 1500, 400, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/shower-installation-cost/'),
  ('electrician', 'EV home charger installation (charger + labour; ~£500 if grant-eligible)', 'per_item', 645, 1092, 1000, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/electric-car-charger-installation-cost/'),
  ('tiler', 'wall tiling (install, labour only)', 'per_m2', 20, 40, null, false, null, 'London tilers command higher day rates (£150-£250/day) than national averages', 'https://www.priceyourjob.co.uk/internal-wall-tiles-cost/'),
  ('tiler', 'wall/floor tiling, standard tiles (labour only)', 'per_m2', 30, 60, null, false, null, null, 'https://www.ratedpeople.com/blog/tiling-cost-guide-wall-and-floor-tiling-rates'),
  ('tiler', 'tiling labour per m2 (wall or floor)', 'per_m2', null, null, 50, false, 300, 'Quite typical for a tiler to charge more in London and the South; hourly rate ~£40', 'https://www.checkatrade.com/blog/cost-guides/tiling-cost/'),
  ('tiler', 'tiling incl adhesive and grout (floors, walls or splashbacks)', 'per_m2', 80, 130, null, true, null, 'London/South East hourly £30-£40 vs £20-£30 Midlands/North (UK range £20-£40/hr)', 'https://www.mybuilder.com/tiling/price-guides/tiling-cost'),
  ('tiler', 'full bathroom tiling, walls and floor (typical bathroom, 3-4 days)', 'per_job', 800, 1200, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/tiling-cost/'),
  ('tiler', 'kitchen splashback (worktop-to-cabinet area, supply and fit)', 'per_job', null, null, 275, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/tiling-cost/'),
  ('tiler', 'kitchen splashback (labour only)', 'per_job', 60, 100, null, false, null, 'UK tiler day rate £140-£200 but may be double in London and the South East', 'https://www.priceyourjob.co.uk/tiler-prices/'),
  ('tiler', 'regrouting a bathroom, walls and floor (~£15/m2)', 'per_job', null, null, 380, true, 320, 'London and South East trades typically charge more than other regions', 'https://www.checkatrade.com/blog/cost-guides/regrouting-cost/'),
  ('tiler', 'regrouting a shower enclosure (silicone reseal adds £50-£100)', 'per_job', null, null, 160, true, 320, null, 'https://www.checkatrade.com/blog/cost-guides/regrouting-cost/'),
  ('tiler', 'removing old tiles, adhesive and grout (whole-room job)', 'per_job', 800, 900, null, false, null, null, 'https://www.checkatrade.com/blog/cost-guides/tiling-cost/'),
  ('tiler', 'large-format tile installation (day rate premium; 10-15m2 laid/day, slower than standard)', 'per_day', 200, 300, 250, false, 250, 'Tiler day rates higher in London and the South East than rest of UK', 'https://www.checkatrade.com/blog/cost-guides/large-format-tile-installation-cost/'),
  ('tiler', 'tiler hourly rate, London', 'per_hour', 30, 35, 34, false, 210, 'London-specific rates from 712+ tilers; day rates £180-£250', 'https://www.hamuch.com/rates/tiler/london'),
  ('plasterer', 'skim a wall', 'per_job', 150, 200, null, true, null, null, 'https://www.priceyourjob.co.uk/plastering-skimming-walls-cost/'),
  ('plasterer', 'skim/re-skim a room (small 2x2m £440, medium 3x3m £480, large 6x5m £650; ~£24/m2)', 'per_job', 378, 690, 480, true, 300, 'Rates may be higher for London and the South East', 'https://www.checkatrade.com/blog/cost-guides/cost-skimming-room/'),
  ('plasterer', 'skim plastering per m2', 'per_m2', 15, 30, 24, null, null, 'Higher prices common in London and the South East (typical £24/m2 figure from Checkatrade cost-skimming-room)', 'https://www.mybuilder.com/plastering-rendering/price-guides/cost-of-plastering'),
  ('plasterer', 'plaster a room in full (small 9m2 £1,100 to large 18m2 £1,900)', 'per_job', 1100, 1900, null, true, 300, 'Rates may be higher for complex work or in London and the South East', 'https://www.checkatrade.com/blog/cost-guides/cost-plaster-room/'),
  ('plasterer', 'skim/plaster a ceiling (small 9m2 £275, medium 15m2 £360, large 25m2 £575)', 'per_job', 200, 725, 360, true, null, 'Labour costs vary between London, the South East and other regions', 'https://www.checkatrade.com/blog/cost-guides/plastering-ceiling-cost/'),
  ('plasterer', 'plasterboard and plaster a ceiling (overboarding a damaged ceiling)', 'per_job', 700, 1000, null, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/plastering-ceiling-cost/'),
  ('plasterer', 'plasterboard walls, supply and fit (skim coat priced separately; ceiling £37/m2)', 'per_m2', null, null, 16, true, null, null, 'https://www.checkatrade.com/blog/cost-guides/cost-put-up-drywall/'),
  ('plasterer', 'patch repair (small area)', 'per_job', 70, 130, null, true, null, null, 'https://www.priceyourjob.co.uk/plastering-skimming-walls-cost/'),
  ('plasterer', 'artex removal or cover, one wall/ceiling (plaster over £150-£250; steam or scrape £150-£200; chemical £250-£500)', 'per_job', 150, 500, null, true, null, null, 'https://www.priceyourjob.co.uk/removing-artex-cost/'),
  ('plasterer', 'plasterer hourly rate, UK', 'per_hour', 15, 50, 25, false, 250, 'London and South East costs approximately 20% higher than national average', 'https://www.ratedpeople.com/blog/plastering-price-guide-how-much-does-plastering-cost'),
  ('plasterer', 'plasterer hourly rate, London', 'per_hour', 20, 45, 34, false, null, 'London-specific rates from 902+ plasterers; day rates £160-£280', 'https://www.hamuch.com/rates/plasterer/london')
on conflict (trade, task) do nothing;
